export const images = {
  backgroundLights: "/images/background/backgroundtitan-lights.webp",
  backgroundTitan: "/images/background/backgroundtitan.webp",
  buttonOff: "/images/header/button-off.webp",
  buttonOn: "/images/header/button-on.webp",
  googlePlay: "/images/header/google-play.webp",
  headerBackground: "/images/header/header-background.webp",
  headerLeft: "/images/header/header-left.png",
  headerMiddle: "/images/header/header-middle.png",
  headerRight: "/images/header/header-right.png",
  escomHeroBattle: "/images/hero/escom-hero-battle.png",
  escomLogo: "/images/hero/escom-logo.png",
  polygon: "/images/hero/polygon.png",
  arch: "/images/parallax/arch.webp",
  city: "/images/parallax/city.webp",
  contractor: "/images/parallax/contractor.webp",
  doorLeft: "/images/parallax/door-left.webp",
  doorRight: "/images/parallax/door-right.webp",
  sky: "/images/parallax/sky.webp",
  middleLayer: "/images/parallax/middle-layer.png",
  logo: "/images/logo.webp",
  robot: "/images/robot.png",
  bannerLeft: "/images/footer/banner-left.webp",
  bannerRight: "/images/footer/banner-right.webp",
  banner: "/images/footer/banner.webp",
  googlePlayFooter: "/images/footer/google-play-footer.webp",
  joinCause: "/images/footer/join-the-common-cause.webp",
  lifeIsGame: "/images/footer/life-is-a-game.webp",
} as const;

export const ICONS = [
  {
    id: "Facebook",
    icon: "/images/icons/facebook-icon.webp",
    route: "https://www.facebook.com/esportEscom",
  },
  {
    id: "Instagram",
    icon: "/images/icons/instagram-icon.webp",
    route: "https://www.instagram.com/Esport_Escom/",
  },
  {
    id: "TikTok",
    icon: "/images/icons/tiktok-icon.webp",
    route: "https://www.tiktok.com/@earthsecuritycomma",
  },
  {
    id: "YouTube",
    icon: "/images/icons/youtube-icon.webp",
    route: "https://www.youtube.com/channel/UC9lAnxCQy5BZ1lB-cNSlO4Q",
  },
] as const;
