export const images = {
	backgroundLights: "/images/background/backgroundtitan-lights.webp",
	backgroundTitan: "/images/background/backgroundtitan.webp",
	buttonOff: "/images/header/button-off.webp",
	buttonOn: "/images/header/button-on.webp",
	googlePlay: "/images/header/google-play.webp",
	headerBackground: "/images/header/header-background.webp",
	headerLeft: "/images/header/header-left.png",
	headerMiddle: "/images/header/header-middle.png",
	headerRight: "/images/header/header-right.png",
	escomHeroBattle: "/images/hero/escom-hero-battle.png",
	escomLogo: "/images/hero/escom-logo.png",
	polygon: "/images/hero/polygon.png",
	arch: "/images/parallax/arch.webp",
	city: "/images/parallax/city.webp",
	contractor: "/images/parallax/contractor.webp",
	doorLeft: "/images/parallax/door-left.webp",
	doorRight: "/images/parallax/door-right.webp",
	sky: "/images/parallax/sky.webp",
	middleLayer: "/images/parallax/middle-layer.png",
	logo: "/images/logo.webp",
	robot: "/images/robot.webp",
} as const;
